### ISSUE TITLE
Possível correção do projeto

### ISSUE THREAD

**Issue by cleversonlira** [andrelucasc/Landing-Page#1]
Andre, beleza?

Segue aqui duas sugestões que pode te ajudar a resolver o problema no seu projeto:

1. **Se basear no scroll do body, ao invés do header**

> Como o header é muito pequeno, é melhor se basear no scroll do body, e então se o scroll do body for maior que zero, você adiciona a classe.
O código do seu script ficaria mais ou menos assim:

```
const body = document.querySelector('body')
const header = document.querySelector('header')

function changeHeaderOnScroll() {
  if (body.scrollTop > 0) {
    header.classList.add('rolling')
  } else {
    header.classList.remove('rolling')
  }
}

body.addEventListener('scroll', () => {
  changeHeaderOnScroll()
})
```

2. **Colocar a chamada do script no final da sua página html**
>Tirar a chamada do script da tag `<head>`, e colocar a chamada do script no final da sua página html antes do fechamento do `</body>`. Pois, visto que o JavaScript vai ficar _escutando o scroll do body_, o body precisa estar completamente carregado.

O código do seu html ficaria mais ou menos assim:
```
<script src="assets/js/script.js"></script>
</body>
```

Parabéns pelo projeto!

**Comment by andrelucasc** [comment]
Obrigado pelo issue, Cleverson!
 Foi de imensa importância as suas sugestões, precisei fazer as duas alterações que você mencionou para que a função funcionasse!
 Irei me aprofundar no JS e entender como o seu código funcionou!
 
 A modificação já consta no último push do repositório.
 #issue fixed
 
[](https://andrelucasc.github.io/Landing-Page/)
 
 Muito obrigado!
